### ISSUE TITLE
[Feat] pencil double tap시 단어선택 - 선택지우기 버튼 간 변환

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#115]
### 📝 작업 목적
- 앱 사용시 pencil 사용이 필수
- pencil사용할 경우 일반적인 User는 pencil double tap을 자주 활용
- Word 선택 - 선택해제간에 버튼으로 전환이 아닌 Double Tap으로 전환기능 구현

---

### 🛠️ Tasks

* [x] 순수 SwiftUI 에서 Double Tap에서 구현가능한지 확인
* [x] SwiftUI에서 구현이 불가능하다면 UIViewRepresentable 형태 구현가능여부 확인
* [x] Double Tap 구현
