### ISSUE TITLE
[Feat] 기기별 좌표 대응 (수동) 

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#118]
### 📝 작업 목적

- 1차 가출시를 위한 iPad기기별 대응 
- iPad 기기별로 글자인식 후 표시 좌표 (반)수동 설정 예정

---

### 🛠️ Tasks

* [x] iPad Pro 12.9 인치 6세대
* [x] iPad Pro 11 인치 4세대
* [x] iPad Air 5세대
* [x] iPad mini 6세대
* [x] iPad 10세대
