### ISSUE TITLE
[Fix] 파일 추가 안되는 버그

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#126]
### 📝 작업 목적

- HomeView에서 [파일 보관함] 기능이 제대로 동작하지 않음
- 안쓰는 print() 지우기
- 기타 chore 작업
---

### 🛠️ Tasks

* [ ] HomeView에서 [파일 보관함] 기능이 제대로 동작하지 않음
* [ ] 안쓰는 print() 지우기
* [ ] 기타 chore 작업
