### ISSUE TITLE
[Feat] 앱 출시를 위한 버전 업데이트

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#130]
### 📝 작업 목적

- 앱 출시를 우한 빌드 업데이트

---

### 🛠️ Tasks

* [x] samplePDF를 제외한 나머지 PDF 파일 삭제
* [x] 전체통계 버튼 버그(+1 되는)로 인한 주석처리
* [x] 사진 파일 선택시 왜 접근 허용메세지 수정(좀 더 자세하게 - 앱출시 반려로인한 수정)
* [x] 가로, 세로 모드에 대한 설정문제 (빌드 세팅에서 조정)

**Comment by Suppppppp** [comment]
작업 후 출시심사 넣었고 출시완료 후 dev에 머지완료
