### ISSUE TITLE
[Feat] 단어 시험전 암기를 위한 연습장 View제작

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#131]
### 📝 작업 목적

- 단어를 암기했는지 시험보기 전에 암기를 위한 연습장이 필요
- 연습장제작
   - 시험보기 전인 OCR Edit에 제작
   - 해당 연습장은 화면에 대략 1/8 정도 크기로 이동이 가능하면 애플펜슬로 낙서가능 

---

### 🛠️ Tasks

* [x] 연습장 제작
* [x] 연습장위에 pencil로 낙서기능
* [x] 연습장 자체가 드래그로 위치 이동
* [x] 버튼 방식으로 연습장을 on/off
