### ISSUE TITLE
[Design] UI변경

### ISSUE THREAD

**Issue by Greeddk** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#133]
### 📝 작업 목적

- 스프린트4에서 바꿔야하는 UI를 변경합니다.
---

### 🛠️ Tasks

* [x] 홈뷰 타이틀 Home으로 변경
* [x] 리저트 페이지에서 정답의 버튼 쉐도우 제거
* [x] 리저트 페이지 정답률 박스 라운드하게 수정
* [x] 오버뷰에서 회차 없을 시 결과보기 버튼 안보이게 하기
* [x] 회차를 선택해야지 원본 버튼 나타나게 하기
* [x] 홈뷰에 파일이 표시되는 개수 늘리기
