### ISSUE TITLE
[Feat] 폴더링 기능(이동까지)

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#136]
### 📝 작업 목적

- 편집 모드 
  - 폴더 만들기
  - 파일 선택 후 내비게이션 바의 이동 버튼을 누르면
    - 폴더 목록에 대한 팝업이 뜸
  
#### 참고 영상
https://github.com/DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank/assets/40187546/9d6008e8-6fc5-4933-a651-69b497faced0

---

### 🛠️ Tasks

* [x] 폴더 표시 및 접근
* [x] 편집 모드에서 폴더 생성 기능
* [x] 폴더 삭제 기능
* [x] 편집 모드에서 파일을 특정 폴더로 이동하는 기능
