### ISSUE TITLE
[Design] UI변경

### ISSUE THREAD

**Issue by Greeddk** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#152]
### 📝 작업 목적

- 오버뷰모달뷰의 데이터 표시 방식 변경 및 데이터 없을때 내용 수정
- 단어선택 설명 바꾸기
---

### 🛠️ Tasks

* [x] 모달뷰의 데이터 나와있는 부분 수정
* [x] 단어 변경 설명 수정
* [x] 리저트페이지 버튼에 이너쉐도우 적용
