### ISSUE TITLE
[Feat] OverView를 제외한 모든 View의 하단 spacer() 영역제거

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#153]
### 📝 작업 목적

- OverView를 제외한 모든 View의 하단 spacer() 영역제거
- spacer를 제거한 영역에 해당 view의 내용으로 채우고 단어에 대한 좌표설정
---

### 🛠️ Tasks

* [x] spacer 제거
* [x] Spacer제거 된 곳에 view내용 크기 조절해서 넣기
* [x] 각 view에 대한 좌표 수정
   * [x] WordSelectView의 단어 좌표 확인
      * [x] 빈칸 frame 직접 만들기 좌표 확인
   * [x] OCREditView의 빈칸 좌표확인
   * [x] ResultPageView의 정답 빈칸 좌표확인
