### ISSUE TITLE
[Feat] HomeView: 파일 목록 가져오기, 섬네일 표시, 검색 기능

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#3]
### 📝 작업 목적

- 앱 Document 폴더에 저장된 파일 목록 표시
- 파일 섬네일 이미지: PDF인 경우와 이미지인 경우를 구분해서 생성
- 검색 기능 추가
---

### 🛠️ Tasks

* [x] Document 폴더의 파일 중 `pdf` 및 이미지 형식의 파일 목록을 뷰 모델로 가져오기
* [x] 섬네일 이미지 생성 기능 추가
* [x] 검색 기능 추가
