### ISSUE TITLE
[Feat] OCREditView Scrrible 설명 모달 추가

### ISSUE THREAD

**Issue by ComaJJo** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#39]
### 📝 작업 목적
OCREditView에 scrrible 설명 모달View 추가

---

### 🛠️ Tasks

* [ ] ScrribleType enum으로 구현
* [ ] ScrribleType별로 텍스트 변경
* [ ] ScrribleType별로 Video 변경
