### ISSUE TITLE
[Design] make OverView

### ISSUE THREAD

**Issue by Greeddk** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#5]
### 📝 작업 목적

- 해당 뷰에 대한 전체 UI 그리기
- 각 버튼을 눌렀을때 필요한 TODO 작성해둠
---

### 🛠️ Tasks

* [ ] 네비게이션바 버튼들, ui 구현
* [ ] 하단 스크롤바 구현
* [ ] 모달뷰 구현
* [ ] 파일 이름 누르면 나오는 팝오버 구현
