### ISSUE TITLE
[Feat] Internal Shocase 작업 브랜치

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#53]
### 📝 작업 목적

- page로 데이터 넘겨주기 가능
- 워드 셀렉트 가능

---

### 🛠️ Tasks

해야할것 :
* [ ] 확대 제스쳐 수정
* [ ] 텍스트 수정
* [ ] 시험시 텍스트 작성
* [ ] 결과 페이지 색깔 수정
