### ISSUE TITLE
[Feat] 글자인식 기준 변경 - 띄어쓰기 to 한 글자씩

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#62]
### 📝 작업 목적

- 글자인식 기준을 기존 띄어쓰기 단위에서 한 글자씩 인식으로 변경

변경이유 : 
1. 띄어쓰기단위 글자 인식으로 인한 인식 정확도 감소 여부를 체크하기 위함
2. 단어 선택방식이 형광펜처럼 그어서(drag gesture) 인식할 때 칠해진 글자까만 인식하기 위해서

---

### 🛠️ Tasks

* [ ] 글자 인식기준 코드 변경 ( 띄어쓰기 -> 한 글자)
* [ ] 인식 정확도 체크
* [ ] 바뀐 방식으로 진행할 경우 SelecteWordView ,OCREditView로 Seleted word 데이터 수정
