### ISSUE TITLE
[Feat] 채점 로직 변경 

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#69]
### 📝 작업 목적

- 채점 로직 변경
---

### 🛠️ Tasks

* [ ] 채점시에는 대소문자 구분없이 글자만 같으면 정답으로 처리한다. 
* [ ] 띄어쓰기 입력은 받되 채점시 고려안함,
* [ ] `.` , `,` 도 입력은 받되 채점시 고려 안함
