### ISSUE TITLE
[Feat] N회차 코어 데이터 설계 및 Overview 구현

### ISSUE THREAD

**Issue by ayaysir** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#74]
### 📝 작업 목적

- 세션이 생성되고 테스트가 끝나면 코어데이터에 세션 데이터를 저장 (`ResultPageView` 및 `ScoringViewModel`)
- 오버뷰에서 현재 페이지에서 세션이 몇 회차 저장되어 있는지 코어데이터로부터 로드 (`OverViewModel`)
- 단어 선택 부분부터 세션은 무조건 새로 생성되어야 하므로 오버뷰 외에서 별도로 코어데이터로부터 세션을 로드할 필요는 없는 것 같음
- (추가) Overview에서 Figma 와이어프레임에 나온 대로 구현
- (Optional) OverView: n회차 분기 (
  - 시험보기 - 이전 단어목록을 그대로 사용해서 Overview로 패스)
  - 수정하기 - 원래 프로세스대로 진행
---

### 🛠️ Tasks

* [x] `ResultPageView`에서 세션 데이터를 코어 데이터에 저장
* [x] `OverViewModel`에서 세션 회차 정보를 코어 데이터로부터 로드
* [x] n회차 메뉴 표시
* [x] 클릭하면 맞고 틀린 단어 표시
* [x] 전체통계 표시
