### ISSUE TITLE
[Feat] WordSelectView에서 word 선택시 하나의 word만 선택이 아닌 drag gesture로 여러 word 선택

### ISSUE THREAD

**Issue by Suppppppp** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#88]
### 📝 작업 목적
- WordSelectView에서 단어 선택시 여러 word를 선택할 수 있게 한다
- WordSelectView의 navigation bar에 버튼을 달아서 선택(형광펜)/ 지우개 버튼을 만든다
- 선택 / 지우기 영역에 대한 인지를 위해 사각형으로 영역을 표시해준다

---

### 🛠️ Tasks

* [x] WordSelectView Navigation bar 선택(형광펜)/ 지우개 버튼 만들기
* [x] drag gesture 적용
* [x] 드래그 영역을 네모로 표시
* [x] WordSelectView 진입시 dafault는 선택(형광펜) 상태 
* [x] 선택(형광펜) 버튼 눌렀을 때 드래그시 word 선택 
* [x] 지우개 버튼 눌렀을 때 드래그시 word 선택 해제
