### ISSUE TITLE
[Feat, Bug] TextField ViewModel 적용 및 버그 픽스

### ISSUE THREAD

**Issue by ComaJJo** [DeveloperAcademy-POSTECH/MacC-Afternoon-Team11-FoursTech-Blank#93]
### 📝 작업 목적
TextField 뷰모델 적용, Padding값 부여, 보라색 문구 버그 픽스
* 보라색 문구 : Accessing State's value outside of being installed on a View. This will result in a constant Binding of the initial value and will not update.

---

### 🛠️ Tasks

* [ ] TextField 뷰모델 적용
* [ ] TextField 좌측 패딩값 부여
* [ ] 보라색 문구 버그 픽스
